name: time_ago_provider
description: library for generating fuzzy timestamp for example ("9 minutes ago")
version: 3.0.0
homepage: https://github.com/BaderEddineOuaich/time_ago_provider
author: Bader Eddine Ouaich <badereddineouaich@gmail.com>

environment:
  sdk: '>=2.12.0-13.0.dev <3.0.0'

dev_dependencies:
  pedantic: "^1.10.0-nullsafety.3"
  test: "^1.16.0-nullsafety.9"
