name: time_ago_provider
description: library for generating fuzzy timestamp for example ("9 minutes ago")
version: 2.2.0
homepage: https://github.com/BaderEddineOuaich/time_ago_provider
author: Bader Eddine Ouaich <badereddineouaich@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
