name: time_ago_provider
description: A Library that takes a time stamp value and returns an interval String of the time that passed between the given time stamp to the present (Now). (e.g. "7 minutes ago" ).
version: 0.1.0+1
homepage: https://github.com/BaderEddineOuaich/time_ago_provider
author: Bader Eddine Ouaich <badereddineouaich@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.5.0
  test: ^1.6.1
